### ISSUE TITLE
About get_cluster_centers

### ISSUE THREAD

**Issue by zhaomengjiao123** [Duanyll/CANConv#1]
In the `canconv.py` file, there is a reference to "from.kmeans import KMeans, get_cluster_centers", but I couldn't find the get_cluster_centers function. How can I solve this issue?

**Comment by Duanyll** [comment]
The two implementations are defined in `canconv/layers/kmeans/cluster_center.py`, and the scatter version is used by default (see https://github.com/Duanyll/CANConv/blob/29fb4fa2be6c52250035c70880fa0987f87a679f/canconv/layers/kmeans/__init__.py#L1). 

Is this issue preventing you from running the code?

**Comment by zhaomengjiao123** [comment]
Thank you for your response. Additionally, I would like to know what libraries are needed if I want to run this in my own virtual environment. I encountered the following issue, and I'm not sure how to resolve it. Your help is greatly appreciated!

Traceback (most recent call last):
File "../canconv/pwac/custome_op.py", line 12, in <module>
c_lib = importlib.import_module("..pwacnative", name)
File "../anaconda3/envs/pytorch/lib/python3.9/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.common.canconv.pwac.pwacnative'

**Comment by Duanyll** [comment]
Please make sure you have successfully executed the build.sh​, as described in the readme file. Other dependency is listed in .devcontainer/Dockerfile​. Note that there are issues that cmake sometimes fails to detect the correct conda virtual environment, so it is suggested to use docker to manage environments.
________________________________
发件人: zhaomengjiao123 ***@***.***>
发送时间: 2024年5月28日 17:34
收件人: Duanyll/CANConv ***@***.***>
抄送: Duanyll ***@***.***>; Comment ***@***.***>
主题: Re: [Duanyll/CANConv] About get_cluster_centers (Issue #1)


Thank you for your response. Additionally, I would like to know what libraries are needed if I want to run this in my own virtual environment. I encountered the following issue, and I'm not sure how to resolve it. Your help is greatly appreciated!

Traceback (most recent call last):
File "../canconv/pwac/custome_op.py", line 12, in
c_lib = importlib.import_module("..pwacnative", name)
File "../anaconda3/envs/pytorch/lib/python3.9/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1030, in _gcd_import
File "", line 1007, in _find_and_load
File "", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.common.canconv.pwac.pwacnative'

**Comment by Duanyll** [comment]
if there is no problem left, i'd like to close this issue. feel free to reopen it or create another one.
