### ISSUE TITLE
😂

### ISSUE THREAD

**Issue by DowneyFlyfan** [Duanyll/CANConv#2]
因为自己的原因，之前在邓老师组没做什么事情，现在不知道在哪开组会了🤣

最近一个月开始集中看了一些文章，虽然脑子慢了点，但还是整天都把时间花在上面😂

有些许进步，但是觉得自己还是水平太菜，不好意思找邓老师的😂

**Comment by Duanyll** [comment]
不是代码问题的话我就把 issue 关了，组里的事情可以私聊我
